# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "att_speech"
  s.version = "0.0.6"

  s.authors = ["Jason Goecke", "Peter Wilson", "Ben Klang"]
  s.description = "A Ruby library for consuming v3 of the AT&T Speech API for speech->text, and text->speech. Takes in either .wav or specific other audio files, and returns a text string of the spoken words. Can also take in either a text string or .txt file and returns a string of bytes from which a .wav file can be created of the spoken text."
  s.email = "dev&adhearsion.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
  s.executables   = `git ls-files -- bin/*`.split("\n").map{ |f| File.basename(f) }
  s.homepage = "http://github.com/adhearsion/att_speech"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.required_ruby_version = '>= 1.9.3'
  s.summary = "A Ruby library for consuming the AT&T Speech API https://developer.att.com/developer/forward.jsp?passedItemId=12500023 for speech->text, and text->speech."

  s.add_runtime_dependency(%q<faraday>, ["~> 0.8.1"])
  s.add_runtime_dependency(%q<celluloid>, [">= 0.11.1"])
  s.add_runtime_dependency(%q<hashie>, [">= 1.2.0"])
  s.add_runtime_dependency(%q<activesupport>, [">= 0"])

  s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
  s.add_development_dependency(%q<yard>, [">= 0.7"])
  s.add_development_dependency(%q<rdoc>, [">= 3.12"])
  s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
  s.add_development_dependency(%q<jeweler>, [">= 1.8.4"])
  s.add_development_dependency(%q<simplecov>, [">= 0"])
  s.add_development_dependency(%q<fakeweb>, [">= 0"])
end

